Fix ref forward issue with veggie burger menu button
I noticed in Sentry that we have a steady stream of the following error:
"s.current.getBoundingClientRect is not a function"

I traced this back to the veggie burger button component which is shown
at mobile widths on subscribe landing pages and was able to recreate
locally. I found that the ref wasn't being forwarded to the underlying
button element correctly.

From React 19 you can just pass as a ref prop, but for the version of
Preact we're on it looks like forwardRef is needed. This should stop the
Sentry error. It also fixes the slightly weird positioning of the close
button when the veggie burger menu is open.