Upgrade identity-auth-play to a preview version
This is to fix a vulnerability with Blaze.

This had some knock on effects:

I had to upgrade the version of scala-uri to fix a binary
incompatibility error because it wanted a different version of
cats-parse.

I had to fix the following compilation error:

[error]
<snip>/support-frontend/support-frontend/app/wiring/Services.scala:58:45:
Could not find an implicit IORuntime.
[error]
[error] Instead of calling unsafe methods directly, consider using
cats.effect.IOApp, which
[error] runs your IO. If integrating with non-functional code or
experimenting in a REPL / Worksheet,
[error] add the following import:
[error]
[error] import cats.effect.unsafe.implicits.global
[error]
[error] Alternatively, you can create an explicit IORuntime value and
put it in implicit scope.
[error] This may be useful if you have a pre-existing fixed thread pool
and/or scheduler which you
[error] wish to use to execute IO programs. Please be sure to review
thread pool best practices to
[error] avoid unintentionally degrading your application performance.
[error]   lazy val oktaAuthService = OktaAuthService(
[error]                                             ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

I went with CoPilot's recommendation and picked the former.