Specify the region explicitly
Without this I see the following error when synthing:

ValidationError: Region is required to enable ELBv2 access logging
at path [Frontend-CODE/LoadBalancerFrontend] in aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationLoadBalancer